"""initial schema

Revision ID: fc448738cc28
Revises: 
Create Date: 2026-07-04 20:42:47.370427

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fc448738cc28'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('blob_key', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sub', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_sub'), 'users', ['sub'], unique=True)
    op.create_table('loads',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shop_name', sa.String(), nullable=True),
    sa.Column('shop_location', sa.String(), nullable=True),
    sa.Column('send_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'sent', 'closed', name='loadstatus', native_enum=False, length=16), nullable=False),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_received', sa.Integer(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_loads_user_id_updated_at_id', 'loads', ['user_id', 'updated_at', 'id'], unique=False)
    op.create_table('photo_links',
    sa.Column('photo_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('load', 'load_item_category', 'load_item', name='photolinkentitytype', native_enum=False, length=32), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'entity_type', 'entity_id', name='uq_photo_links_photo_entity')
    )
    op.create_index('ix_photo_links_entity_type_entity_id', 'photo_links', ['entity_type', 'entity_id'], unique=False)
    op.create_table('load_item_categories',
    sa.Column('load_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('count_sent', sa.Integer(), nullable=False),
    sa.Column('count_received', sa.Integer(), nullable=True),
    sa.Column('count_mode', sa.Enum('auto', 'manual', name='countmode', native_enum=False, length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_load_item_categories_load_id_updated_at_id', 'load_item_categories', ['load_id', 'updated_at', 'id'], unique=False)
    op.create_table('load_items',
    sa.Column('load_item_category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['load_item_category_id'], ['load_item_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_load_items_load_item_category_id_updated_at_id', 'load_items', ['load_item_category_id', 'updated_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_load_items_load_item_category_id_updated_at_id', table_name='load_items')
    op.drop_table('load_items')
    op.drop_index('ix_load_item_categories_load_id_updated_at_id', table_name='load_item_categories')
    op.drop_table('load_item_categories')
    op.drop_index('ix_photo_links_entity_type_entity_id', table_name='photo_links')
    op.drop_table('photo_links')
    op.drop_index('ix_loads_user_id_updated_at_id', table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_users_sub'), table_name='users')
    op.drop_table('users')
    op.drop_table('photos')
    # ### end Alembic commands ###
