import os

from clothesline_db.url import adonet_to_asyncpg_url
from pydantic_settings import BaseSettings, SettingsConfigDict


def _resolve_database_url() -> str:
    # Aspire injects `ConnectionStrings__<resourcename>` for referenced resources.
    raw = os.environ.get("ConnectionStrings__clothesline_db")
    if raw:
        # Aspire's generated connection string carries no SSL mode, and in Azure
        # it arrives via a Key Vault secret reference we can't append to — so the
        # AppHost passes the requirement separately. Azure Postgres enforces TLS;
        # the local container has it disabled (spec §5.6b).
        return adonet_to_asyncpg_url(raw, ssl_mode=os.environ.get("DB_SSL_MODE") or None)
    return "postgresql+asyncpg://postgres:postgres@localhost:5432/clothesline_db"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(extra="ignore")

    database_url: str = _resolve_database_url()
    allowed_origins: str = os.environ.get("ALLOWED_ORIGINS", "*")
    oidc_issuer: str = os.environ.get("OIDC_ISSUER", "")
    oidc_jwks_url: str = os.environ.get("OIDC_JWKS_URL", "")
    oidc_userinfo_url: str = os.environ.get("OIDC_USERINFO_URL", "")

    # Served to the browser over GET /config. The client_id is generated by
    # Zitadel when the OIDC app is registered — it cannot exist when the web
    # bundle is built, so the frontend fetches it at boot rather than having it
    # compiled in. Public by OIDC design: a public client's id is not a secret.
    oidc_client_id: str = os.environ.get("OIDC_CLIENT_ID", "")
    # Optional. Lets a moved or renamed API correct the base URL that *was*
    # baked into the bundle at build time, without rebuilding it.
    api_base_url: str = os.environ.get("API_BASE_URL", "")

    # Azurite locally (a full connection string), a bare service URI + managed
    # identity in Azure — media/blob.py branches on which one it got.
    blob_connection_string: str = os.environ.get("ConnectionStrings__blobs", "")
    blob_container: str = os.environ.get("BLOB_CONTAINER", "photos")
    # See media/blob.py — the SDK's default is ahead of what Azurite accepts.
    blob_api_version: str = os.environ.get("BLOB_API_VERSION", "2025-01-05")
    # The origin the *browser* reaches Blob on, when that differs from the
    # one the API reaches it on (Codespaces port forwarding). Empty in Azure,
    # where both are the same public account endpoint.
    blob_public_origin: str = os.environ.get("BLOB_PUBLIC_ORIGIN", "")

    @property
    def allowed_origins_list(self) -> list[str]:
        return [origin.strip() for origin in self.allowed_origins.split(",") if origin.strip()]


settings = Settings()
